version: 0.2

phases:
  pre_build:
    commands:
      - pip install awscli --upgrade --user
      - npm install -g yarn
  build:
    commands:
      - yarn install
      - CTF_SPACE_ID=vrsagmse1qfb CTF_CDA_ACCESS_TOKEN=5d3d838e7be39328a3f20175aafa937201e308d0bb10498d3283361db3aa1654 yarn run generate
  post_build:
    commands:
      - ln -s /usr/local/bin/nodejs /usr/bin/node
      - yarn run deploy
