version: '3'

services:

  node:
    image: node:14-alpine
    tty: true
    working_dir: /var/www
    command: yarn run dev
    ports:
      - 3000:3000
    volumes:
      - .:/var/www
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    env_file:
      - .env
